### ISSUE TITLE
 "failed to load routines: "no body""

### ISSUE THREAD

**Issue by 877dev** [Apollon77/alexa-remote#103]
Hey Apollon77,

Sorry for being lazy, but there is whole issue here that seems to be linked to your alexa-remote.
Would you be able to weigh in?

https://github.com/586837r/node-red-contrib-alexa-remote2/issues/191

**Comment by Apollon77** [comment]
Yes ... updte to latest version and check changelog please

3.6.0 (2021-01-28)

    (Apollon77) Adjust to new automations (Routines) route
    (Apollon77) Add getAllDeviceVolumes method
    (Apollon77) Return relationships in getSmarthomeDevices call

**Comment by 877dev** [comment]
@Apollon77 thanks, but I have updated to your latest 3.6.0, albeit by manually copying over the **"alexa-remote.js /  alexa-wsmqtt.js, / package.json"** files...

Could you give a hint, I'm not asking you to fix it of course! :)

PS what does "Adjust to new automations (Routines) route" actually mean, did Amazon change something? Might explain the JSON errors?

**Comment by Apollon77** [comment]
The "authentication no json" errors are unknown so far to me. I never saw them till now ... i can only say "try gain" ... no idea what amazon is doing here ... else I need full debug log

**Comment by 877dev** [comment]
Thank you, I'll upload a full debug log soon if you feel like taking a look. Hopefully Amazon might "un-break" it :)

**Comment by 877dev** [comment]
@Apollon77 paste from debug log https://pastebin.com/zyGAd7Xz

I moved the alexa node, redeployed, then this error.....

Here's a snippet:
```
29 Jan 17:32:40 - [debug] [alexa-remote-account:f24a22c6.8037c] Alexa-Remote: Use as Login-Amazon-URL: amazon.co.uk
 
 
29 Jan 17:32:40 - [debug] [alexa-remote-account:f24a22c6.8037c] Alexa-Remote: Use as Base-URL: alexa.amazon.co.uk
 
 
29 Jan 17:32:40 - [debug] [alexa-remote-account:f24a22c6.8037c] Alexa-Remote: cookie was provided
 
 
29 Jan 17:32:40 - [debug] [alexa-remote-account:f24a22c6.8037c] Alexa-Remote: Sending Request with {"host":"alexa.amazon.co.uk","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
 
 
29 Jan 17:32:41 - [debug] [alexa-remote-account:f24a22c6.8037c] Alexa-Remote: Response: No/Invalid JSON
 
 
29 Jan 17:32:41 - [error] [alexa-remote-account:f24a22c6.8037c] Error while checking Authentication: Error: no JSON
```

**Comment by Apollon77** [comment]
Then honestly ... no idea ... I also have no account on .co.uk ... can you please show the configuration?

**Comment by 877dev** [comment]
> can you please show the configuration?

Sure no problem, which configuration files do you need?

**Comment by Apollon77** [comment]
In fact which parameter are used to call the library

**Comment by 877cms** [comment]
> In fact which parameter are used to call the library

Not sure sorry. How do I check that?
