### ISSUE TITLE
Muted

### ISSUE THREAD

**Issue by skillix** [Apollon77/alexa-remote#105]
Hello,

Sorry for my bad English.

The Mute command does not appear to exist.

While the value is well up in the PUSH_VOLUME_CHANGE

Is it possible to add it?

The goal is to take into account the mutated for an announcement or to "make speak" to restore it after the announcement.

**Comment by Apollon77** [comment]
There is no "Mute" command ... basically set volume to 0. A muted status is in the "Player" section where also volume is

**Comment by skillix** [comment]
No, for the streaming player (Freebox Delta Devialet), FireStick and Fire Cube, Mute exists and is used

**Comment by Apollon77** [comment]
Ok, then wehere exactly you miss it? which devices? maybe show screenshots of states

**Comment by skillix** [comment]
sorry I am not an expert, I open the info muted in the "AllDeviceVolume"

alertVolume : null
deviceType : A1X92YQU8MWAPD
dsn : c02eacdbcba640f29ae6e5589e2a7b1c
error : null
speakerMuted : true
speakerVolume : 49

if the command is available in the player part that may be suitable for me, but I did not find it

My alexa is included in my TV decoder

Type A1X92YQU8MWAPD
Familly UNKNOWN

In concrete situhation, in the scenarios I make Alexa speak of my decoder (with integrated speaker) the announcement is made at the volume adjust plus resets the volume to its previous volume, but if the TV was Muted, then it reacted as if the TV was not mutated before the announcement

**Comment by Apollon77** [comment]
No, sorry I was thinking wrong ... we are onm API level only here ... I did not saw that from your request.

But honestly I still do not get you ... Do you say that you send out "mute" but the device it not reacting to it correctly? Or what?

**Comment by skillix** [comment]
then, I mute with the vocal "alexa cut the sound", the sound is deactivated but the volume Y is memorized / active (see image)
but after I make the speaker speak with a volume X, the mute is deactivated, the announcement is made at volume X, then after the announcement the lastsound Y is restored, but without the mute.

But in our jeedom plugin, to be able to manage and restore the volume, we need to have the mute command to be able to restore it.
![IMG_20210217_101327](https://user-images.githubusercontent.com/68369861/108183187-24721500-710a-11eb-9dc0-c8668b169065.jpg)
![IMG_20210217_101259](https://user-images.githubusercontent.com/68369861/108183201-26d46f00-710a-11eb-8e7c-160b0e8c9f7d.jpg)
![image](https://user-images.githubusercontent.com/68369861/108183320-41a6e380-710a-11eb-8ac2-83706ba254ff.png)

**Comment by Apollon77** [comment]
The API is using the API from the Alexa Mobile App. Do you have any way to "mute" a device there? I do not know of any really that would have the same effect. If you find a routine action or other "Button" in teh alexa app that brings that result then tell me and I can tyr to find out what command is sent in the background
You could try to use the new "textCommand" feature and send "cut the voice" to the device as you do with voice.

**Comment by skillix** [comment]
`[2/17/2021, 9:49:44 AM][INFO] :  {API}    ╔═══════[Lancement /textCommand avec paramètres -> device: c02eacdbcba640f29ae6e5589e2a7b1c & text: coupe le son══════════════════════════════════
[2/17/2021, 9:49:44 AM][DEBUG] : {Remote} ║ Sending Request with {"host":"alexa.amazon.fr","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}} and data={"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"operationPayload\":{\"deviceType\":\"A1X92YQU8MWAPD\",\"deviceSerialNumber\":\"c02eacdbcba640f29ae6e5589e2a7b1c\",\"locale\":\"fr-FR\",\"customerId\":\"A3T9PVE5NO04DQ\",\"text\":\"coupe le son\"},\"type\":\"Alexa.TextCommand\",\"skillId\":\"amzn1.ask.1p.tellalexa\"}}","status":"ENABLED"}
[2/17/2021, 9:49:44 AM][DEBUG] : {Remote} ║ Response: No body
[2/17/2021, 9:49:45 AM][DEBUG] : {MQTT}   ╠═══> Command --{PUSH_ACTIVITY}-- : détail désactivé
[2/17/2021, 9:49:45 AM][DEBUG] : {MQTT}   ╠═══> Command --{PUSH_ACTIVITY}-- : détail désactivé
[2/17/2021, 9:49:45 AM][DEBUG] : {MQTT}   ╠═══> Command --{PUSH_VOLUME_CHANGE}-- : détail désactivé
[2/17/2021, 9:49:45 AM][DEBUG] : {Remote} ║ URL envoyée: http://192.168.0.32/plugins/alexaapi/core/php/jeeAlexaapi.php?apikey=AvOVNLaviawIIPXWJmPI9AePPMPEq0VH&nom=ws-volume-change
[2/17/2021, 9:49:45 AM][DEBUG] : {Remote} ║ DATA envoyé:{"destinationUserId":"A3T9PVE5NO04DQ","deviceSerialNumber":"c02eacdbcba640f29ae6e5589e2a7b1c","deviceType":"A1X92YQU8MWAPD","isMuted":true,"volume":23}`

the fonction exists in the routine:
device settings / stop audio / select device (in french : parametre de l'appareil / arret de l'audio)

![Screenshot_2021-02-17-11-02-20-613_com amazon dee app](https://user-images.githubusercontent.com/68369861/108189060-9baaa780-7110-11eb-8cc4-c654eb5e8375.jpg)
![Screenshot_2021-02-17-11-02-34-919_com amazon dee app](https://user-images.githubusercontent.com/68369861/108189066-9e0d0180-7110-11eb-9694-78be6930b484.jpg)
![Screenshot_2021-02-17-11-02-53-646_com amazon dee app](https://user-images.githubusercontent.com/68369861/108189073-9fd6c500-7110-11eb-98a9-9b0ed66dd546.jpg)

**Comment by Apollon77** [comment]
Then it shopuld be he "deviceStop" command.

the "do not disturb" should be controllable already with setDoNotDisturb

**Comment by skillix** [comment]
ok thx, i will try with my developer

**Comment by Apollon77** [comment]
please report back with your results ... else I need to check on commands from the app and such

**Comment by skillix** [comment]
no problem

**Comment by skillix** [comment]
fail !  it stops alexa speaking or when a music is playing

**Comment by skillix** [comment]
```
{
  "directive": {
    "header": {
      "namespace": "Alexa.Speaker",
      "name": "SetMute",
      "messageId": "<message id>",
      "correlationToken": "<an opaque correlation token>",
      "payloadVersion": "3"
    },
    "endpoint": {
      "scope": {
        "type": "BearerToken",
        "token": "<an OAuth2 bearer token>"
      },
      "endpointId": "<endpoint id>",
      "cookie": {}
    },
    "payload": {
      "mute": true
    }
  }
}
```

https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-speaker.html

it's not that ?

**Comment by Apollon77** [comment]
> it's not that ?

this is is skill stuff, as said above the library uses only the "same api then the mobile app" ... so effectively: we can only do it when mobile app can do it. And have in mind: here nothing is "officially provided by amazon" ...

**Comment by Apollon77** [comment]
> fail ! it stops alexa speaking or when a music is playing

but I thought you tested it that the result is that it sents mute but leaves volume intact?!

**Comment by skillix** [comment]
no I did not test it with a routine, I had the option "stop audio".
I will search a little longer, otherwise we will simulate with a text command:

if isMuted = true ==> textCommand "mute the sound"

thanks anyway

**Comment by Apollon77** [comment]
Ok, if you find a routine action or any "button in the mobile app" that achieves what you need tell me what and we can integrate it
