### ISSUE TITLE
Simulate Wake Word?

### ISSUE THREAD

**Issue by barrtailor** [Apollon77/alexa-remote#114]
**Is your feature request related to a problem? Please describe.**
Is there a way that we can programmatically simulate the saying of the wake word?

**Describe the solution you'd like**
I'd like to be able to drop it into a node red flow and have Alexa listen as if I said the wake word at a certain point in the flow

**Describe alternatives you've considered**
Just saying it manually

**Additional context**
N/A

**Comment by Apollon77** [comment]
No, you can not activate teh device from external. Only person interactions are an allowed trigger right now (unless it somes from a skill or such)

**Comment by barrtailor** [comment]
Thank you for clarifying that!
