### ISSUE TITLE
Refresh cookie

### ISSUE THREAD

**Issue by skillix** [Apollon77/alexa-remote#118]
Hello, no problem with the automatic refresh of the cookie since 06/01/21?

**Comment by bwims** [comment]
I think Amazon have been modifying their software again.   Alexa-remote2 relies on this software and someone found a fix for what was preventing us from working.  Maybe it will ring some bells with the maintainer?

https://github.com/cakebake/node-red-contrib-alexa-remote-cakebaked/issues/22#issuecomment-853171093

**Comment by peteakalad** [comment]
PR #117 may fix

**Comment by skillix** [comment]
perfect !

**Comment by Apollon77** [comment]
v3.8.1 will be on npm soon

**Comment by Matten-Matten** [comment]
Großen Dank @Apollon77 !!! Was würden wir nur ohne dich machen.

Gruß
Matten Matten

**Comment by skillix** [comment]
thx !
