### ISSUE TITLE
A way to detect when alexa finishes speaking

### ISSUE THREAD

**Issue by ajithvasudevan** [Apollon77/alexa-remote#122]
When using multiple "speak" commands, sometimes Alexa's speech tends to overlap due to not enough gap between commands. This results in cutting off the first message. If there is a way to detect when Alexa finished  speaking from a previous command, this situation can be avoided.

An event that can let me know when Alexa finishes with the actual speech output (media player stopped?) would be nice.

Currently, I am having to guess the time it takes Alexa to speak a given sentence. This is not very accurate.

BTW, this is an awesome project. It has breathed in new life into my home automation! Thanks for the great work you're doing!

**Comment by Apollon77** [comment]
Sorry, but no real chance right now ... sorry
