### ISSUE TITLE
How Launch Skill?

### ISSUE THREAD

**Issue by guilhermelirio** [Apollon77/alexa-remote#124]
Good Morning! Is there any way to invoke skills?

**Comment by Apollon77** [comment]
basically yes it could be implemented because also the Alexa App allows it ... issue is that it was not really making sense till now becase you need to use the internal skill names and such that nearly noone knows ... But if you think it makes sense it could be implemented

**Comment by guilhermelirio** [comment]
I'm Alexa's skill developer, so it would be to use my own.

Would you have an invocation example?

**Comment by Apollon77** [comment]
I think the call itself is not implemented so far. I need to get some time to retrieve it from the Alexa App and implement it. YOu you try and do a PR :-) I could gve you instructions on how to "grab" it

**Comment by guilhermelirio** [comment]
Of course, for me it can be. I try to develop here. Just give me the instructions!

**Comment by Apollon77** [comment]
Install Charles Proxy on your computer (needs to be in same network as your mobile devie where alexa app is on).
Enable SSL Proxying in Charles and prepare the certifiacate stuff (https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) and install on your phone.
Then setup your PC IP on port 8888 (default charles, changeable) as your WLAN proxy ... instructions also on Charles webpage.

Check with a normal webpage or such that you see it on Charles when you do something on your mobile. If you only see "CONNECT" messages in charles then SSL is not correct somewhere. When you see real GET/POST or such and content you are ready.

Now open Alexa App and you see all the requests the app is doing ... go to the place where you can do that via the app and you see what the app is sending ... post here (or if too sensible send me via email to github@fischer-ka.de) and we check together what and where to implement

**Comment by bwims** [comment]
The simplest thing for me is to use a custom routine that invokes the skill and call that... though I am using the Node Red implementation.

**Comment by guilhermelirio** [comment]
I'm discovery something:

```
    "sequence": {
      "@type": "com.amazon.alexa.behaviors.model.Sequence",
      "sequenceId": "amzn1.alexa.sequence.80f02089-491a-4c26-a64d-35540d3e290e",
      "startNode": {
        "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
        "nodeState": null,
        "name": null,
        "type": "Alexa.Operation.SkillConnections.Launch",
        "skillId": "amzn1.ask.skill.ad29f3ba-d5d0-421f-a394-15be41ce450e",
        "operationPayload": {
          "customerId": "XXXXXXXXXXXXXX",
          "targetDevice": {
            "deviceType": "ALEXA_CURRENT_DEVICE_TYPE",
            "deviceSerialNumber": "ALEXA_CURRENT_DSN"
          },
          "connectionRequest": {
            "uri": "connection://AMAZON.Launch/amzn1.ask.skill.ad29f3ba-d5d0-421f-a394-15be41ce450e",
            "input": {
              
            }
          },
          "locale": "pt-BR"
        },
        "presentationDataList": null,
        "clientData": null,
        "context": null,
        "tag": null
      }
    },
```

This sequenceId it's because I put it in a routine. But I don't know if it's necessary.
