### ISSUE TITLE
Authentication failed: "no body"

### ISSUE THREAD

**Issue by sergiobaiao** [Apollon77/alexa-remote#128]
Hi there,

Yesterday i setup my first Alexa flow in NR, and it was working just fine until today. When i checked the NR container log, i saw this:

15 Aug 00:00:12 - [error] [alexa-remote-account:a1f53caf897d8eb2] Authentication failed: "no body"

and it stopped working just after this.

What should i do?

I`m using the latest version of alexa-remote (3.9.0)

**Comment by Apollon77** [comment]
No other user reported issues so far ... so honestly: Try to get a new proxy and try again... Else I need a full log please not just one line without any context

**Comment by sergiobaiao** [comment]
sorry about that... just restarted my container to test, and it happened again:

15 Aug 20:07:02 - [info]

Welcome to Node-RED
===================

15 Aug 20:07:02 - [info] Node-RED version: v2.0.5
15 Aug 20:07:02 - [info] Node.js  version: v14.17.3
15 Aug 20:07:02 - [info] Linux 5.11.0-25-generic x64 LE
15 Aug 20:07:02 - [info] Loading palette nodes
Sun, 15 Aug 2021 23:07:03 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:1085:14
15 Aug 20:07:03 - [info] RedBot version: 0.19.7 (node-red-contrib-chatbot)
15 Aug 20:07:05 - [info] Dashboard version 2.30.0 started at /ui
15 Aug 20:07:05 - [info] Settings file  : /data/settings.js
15 Aug 20:07:05 - [info] Context store  : 'default' [module=localfilesystem]
15 Aug 20:07:05 - [info] User directory : /data
15 Aug 20:07:05 - [info] Projects directory: /data/projects
15 Aug 20:07:05 - [warn] No active project : using default flows file
15 Aug 20:07:05 - [info] Flows file     : /data/flows.json
15 Aug 20:07:05 - [info] Server now running at http://127.0.0.1:1880/
15 Aug 20:07:05 - [info] Starting flows
15 Aug 20:07:05 - [info] Started flows
15 Aug 20:07:05 - [info] [server:Home Assistant] Connecting to http://192.168.0.244:8123
15 Aug 20:07:05 - [info] [alexa-remote-account:Amazon Account] intialising "Amazon Account" with the PROXY method and saved data...
15 Aug 20:07:05 - [info] [server:Home Assistant] Connected to http://192.168.0.244:8123
15 Aug 20:07:07 - [error] [alexa-remote-account:Amazon Account] Authentication failed: "no body"

If you need any specific logging, please provide information, since the node-red process doesn`t log to file, i`m just getting the docker container log.

**Comment by Apollon77** [comment]
honestly ... this logging do not help me, i need the logging that my lib produces. please check with the node-red flow dev how to activate that logging. thank you

**Comment by sergiobaiao** [comment]
Well, i'm the node-red flow "dev"...actually, i'm just starting with node-red. I'm not sure if this is actually what you want, but i've enabled trace logging in settings.js and this is the output when i've restarted NR.

`
[nodered.log](https://github.com/Apollon77/alexa-remote/files/6992155/nodered.log)
`

**Comment by Apollon77** [comment]
I think that node-red trace do not help here.

The alexa-remote lib allows to provide a logger function (see e.g. https://github.com/Apollon77/alexa-remote/blob/20502e224ef8e4f7a78fcef96ca1df0a14886bb5/example/example.js#L18) ... provide that and use it to get the log from the lib. That i would need

**Comment by Apollon77** [comment]
No response, close
