### ISSUE TITLE
FIXED: Push Connection (WS-MQTT) not working correctly since 29.09.2021

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/alexa-remote#132]
It seems that Amazon broke or changed something - we will see this in some days ... The push connection is not able to connect.

if you are experienced in network analyssis (wireshark or such) please contact me

If you are a user affected by the issue please DO NOT post a "mee too" comment, but "thumbs up" here please

**Comment by fbeister** [comment]
Did you already do an analysis? I don't have a dev environment for NodeJS available but might be of help. Is there a problem with the connection itself or with the data going through the websocket?

If I read it correctly, then Alexa uses TLS over HTTPS and expects a specific certificate for https://dp-gw-na... - which would make a MITM analyis for the data quite hard.

If you would like some outside opinion on what you already did, feel free to contact me.

**Comment by Apollon77** [comment]
Our current status is:
* webpage like alexa.amazon.de is still also trying to open that connection but also is not getting any answer. Because of that  there is still a chance that they just broke it and will fix... or they do not care about those webpage anymore. But in fact it is "normal SSL" that was used for that WebSocket connection, so you can see whats in there in the browser and also in Charles proxy
* We analyzed for HTTPS traffic from the current alexa-app version and there NO such Websocket connection is done anymore ( there seems to be one long-polling connection but no data flow over this which is relevant)
* But because of the fact that the app can show data changes directly there needs to be another connection (maybe they switched to real MQTT or such)

So next steps would be to check using wireshark to see what kind of connection is used to get that traffic ... once we know that we also know if it is encrypted or not and what we need to do. But especially for that we are not experts

**Comment by Apollon77** [comment]
@fbeister write me on iobroker@fischer-ka.de

**Comment by Apollon77** [comment]
There are first international reports that it starts working again. For me personally it is right now not yet working ... but lets wait ...

**Comment by Cjkeenan** [comment]
I use https://github.com/cakebake/node-red-contrib-alexa-remote-cakebaked and I swore I saw it working for a second about a minute ago, but I force restarted my flows and now it isn't...I will keep you posted if anything changes.

**Comment by Matten-Matten** [comment]
Ok, bei meinem System (über) NodeRed läuft es noch nicht. Was sich geändert hat ist der Zustand vom disconnect  Node. Von true auf false. Also passiert ist etwas.

Gruß
matten matten

**Comment by richsimpson** [comment]
I just had the blue spinning circle on mine in the UK, checked and no data coming in to the activity node and in HASS Dev Tools there is still a long delay (30 - 60 Secs) to show the last called info (timestamp, summary and last_called true/false)

**Comment by ftsguy** [comment]
I saw some payloads come in mine on the US feed around 6 to 930 am EST but than it stopped. I also noticed that the payload.activityStatus was missing which I was using so seems some payload changes may be occurring as well.

**Comment by ftsguy** [comment]
Its back up for me now currently 12 pm EST US. I had to update my flows to stop using payload.activityStatus

**Comment by richsimpson** [comment]
I am seeing my "last called", "last called timestamp", "last called summary" and "media position" updating quickly in Home Assistant now when I talk to her, the "on activity", "volume change" options from the Alexa Event node is doing nothing still

**Comment by Cjkeenan** [comment]
It seems to be back up and running for me now. USA

**Comment by Matten-Matten** [comment]
Bei mir Läuft es jetzt auch wieder.

**Comment by madroid225** [comment]
In Italy too seems to be back online! Yep!

**Comment by Apollon77** [comment]
Germany also ... I had zwo errors but third reconnect try worked ... so seems really Amazon issue ... puuhhhh :-)

I will leave here open for reference for some days

**Comment by developerRQS** [comment]
It appears to be back down again in US.

**Comment by Apollon77** [comment]
... also for me ... no idea why they do there

**Comment by elgerg** [comment]
It appears to be working here (UK) where it was broken a few days ago. No need to re-init (i have node red do that every 4 hours anyway)....

**Comment by Cjkeenan** [comment]
It is still working for me (US)

**Comment by Apollon77** [comment]
Ok, for me (DE) also working again on first try

**Comment by sicampbell82** [comment]
I can confirm that in the UK mine has been on and off for the last 3 day.
I've stopped trying to fix it since i realized it seems intermittent issue rather than broken flow on my end

Last night status = down
Current status = working ok.

**Comment by sicampbell82** [comment]
Down for me again to since teatime yesterday

**Comment by Cjkeenan** [comment]
Also down for me now. Cookie refresh doesn't help.

**Comment by Apollon77** [comment]
Yes seems they broke or changed it again.

We are on it already ... when all works out maybe tomorrow night. Can't promise anything

**Comment by ftsguy** [comment]
just confirming US dead as well

**Comment by MattL0** [comment]
with the new code it is working now with nodered. I have forked a nodered repo and used your new code on this github.

I do not intend to manage issues, so maybe people are better to wait for the other node-red forks. Just wanted to update you.

**Comment by Apollon77** [comment]
@MattL0 be patient please ... I'm still in testing phase ...

**Comment by bbindreiter** [comment]
I'll update applestrudel later today. Thanks for your hard work @Apollon77

**Comment by obaldius** [comment]
@quadhammer and @Apollon77 thanks and sorry for the misunderstanding. I hope cakebaked updates soon.

**Comment by Cjkeenan** [comment]
For any NR users, I would recommend an in place upgrade via npm to applestrudel as that version has it working again. Here is a quick guide that I followed: https://tech.scargill.net/node-red-contrib-alexa-cakebaked/

**Comment by Apollon77** [comment]
Without any log I can not see anything - the library itself from me accets a logger function ... no idea how this logging can be forced by the node-red node

**Comment by Cjkeenan** [comment]
Yeah I am not too sure either how to force it. Maybe @bbindreiter or @cakebake might know?

**Comment by quadhammer** [comment]
> For any NR users, I would recommend an in place upgrade via npm versus the palette manager to applestrudel as that version has it working again. Here is a quick guide that I followed: https://tech.scargill.net/node-red-contrib-alexa-cakebaked/

I just updated via the palette manager inside Node Red, and Applestrudel is working again!  Yay! :D

But for future reference, where is the NPM command line thing located?  I'm running Node Red inside Home Assistant inside a VM, so it that something that's even possible?

Cheers

**Comment by Cjkeenan** [comment]
> But for future reference, where is the NPM command line thing located? I'm running Node Red inside Home Assistant inside a VM, so it that something that's even possible?

Not sure about that specific setup, but on my setup I was just running it from my .node-red directory.

**Comment by MattL0** [comment]
The simplest way to update to a diff contrib via palette manager is :
1- Export ALL your tab into a json via export function of nodered (copy it into notepad).
2- Delete all your Nodered Tabs.
3- Delete alexaremote config node but take a screenshot before. 
4- Remove old Alexa-remote contrib from the palette manager.
5- Install the new Alexa-remote package from palette manager .
6- Import json to recover your flows (see json from #1).
7- redo setup to initiate account.

You can also export import only flow related to alexa-remote but it is more error prone.

**Comment by MattL0** [comment]
Edited my last post while you where writing yours haha. Npm is by far easier.

Sent from an Iphone
________________________________
De : Colin Keenan ***@***.***>
Envoyé : Monday, October 11, 2021 10:13:03 PM
À : Apollon77/alexa-remote ***@***.***>
Cc : MattL0 ***@***.***>; Mention ***@***.***>
Objet : Re: [Apollon77/alexa-remote] Push Connection (WS-MQTT) not working correctly since 29.09.2021 (#132)


Yeah while that is technically the "simplest" I would in no way call that simple. Especially if you have multiple flows. The NPM method:

  1.  Locate and cd to the node-red home directory
  2.  npm remove
  3.  npm install
  4.  Restart Node-RED
