### ISSUE TITLE
Question: Can I get device status changes notifications?

### ISSUE THREAD

**Issue by juancgalvez** [Apollon77/alexa-remote#137]
**Is your feature request related to a problem? Please describe.**
This not a problem. Probably a feature request if not already implemented. I have read available documentation and issues and have not found it.

I would like to be able to receive devices status change notifications to have current devices status locally. Basically on lights.

**Describe the solution you'd like**
Receive notifications when the devices status change. Not Echo devices status but lights.

**Describe alternatives you've considered**
Currently most of my devices are eWelink supported devices and I am using a node-red node to get notifications about these devices status changes, but I adding some Tuya devices and there is no node that allows me to do what I want without creating a developer account, something that costs money,

**Additional context**
None.

**Comment by Apollon77** [comment]
Amazon is not pushing such informations, they are only available using polling. sorry
