### ISSUE TITLE
Uncaught Null Exception After Repeated Initialisation

### ISSUE THREAD

**Issue by peteakalad** [Apollon77/alexa-remote#142]
**Describe the bug**  
Using apple strudel node red module, exception occurs if I have a flow which has triggers alexa initialisation in quick succession.  This causes node red service to crash/stop.

I resolved by adding to alexa-wsmqtt.js at line 329 to check for null object i.e. first line below added:
```
                    if (!this.websocket) return;
                    this.websocket.send(msg);
```

Node Red Log:
```
1 Nov 13:48:39 - [info] [alexa-remote-account:Alexa] intialising "Alexa" with the PROXY method and saved data...
1 Nov 13:48:39 - [info] [alexa-remote-account:Alexa] intialising "Alexa" with the PROXY method and saved data...
1 Nov 13:48:40 - [red] Uncaught Exception:
1 Nov 13:48:40 - [error] TypeError: Cannot read property 'send' of null
    at Timeout._onTimeout (/home/nodered/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/node_modules/alexa-remote2/alexa-wsmqtt.js:329:36)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**To Reproduce**  
1. Initialise twice in quick sucession.

**Expected behavior**  
Module should not throw unhandled exception.

**Versions:**  
 Using version 4.0.3 referenced by the latest version of the applestrudel node red module.

**Additional context**  
I acknowledge node red flow should not be initialising twice in quick succession but it also shouldnt cause node red to crash altogether.

Thanks for the module!

**Comment by Apollon77** [comment]
Yes will come with next version ... aloready fixed on my local branch
