### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by softwaretech** [Apollon77/alexa-remote#170]
I'm wondering if, when on logs in to amazon using localhost:6543, is there a way to stay logged in even if I restart my system?

**Comment by Apollon77** [comment]
Sure ... check exmaple ... you get registration data including tpokens and such back in the callback when a user logs in and you need to store this and thenyou provide this in the call next time in formerRegistrationData and then this should be all automatically refreshed and used

**Comment by Apollon77** [comment]
PS: you also need to store macDms  and re-provide
