### ISSUE TITLE
Alexa web page localhost:3456 don't have hte username and password fields for login

### ISSUE THREAD

**Issue by Mirco980** [Apollon77/alexa-remote#217]
**Describe the bug**  

Hi, when I create a new instance of node-red and use the fork "node-red-contrib-alexa-remote2-applestrudel" I try to authenticate via proxy on Alexa, the web page to enter the username and password does not have the fields to login.
Currently the Alexa page localhost:3456  appears with a QR code and it is no longer possible to capture the cookie.

**To Reproduce**  
1. Go to 'Init alexa node'
2. Click on 'add new account'
3. Scroll down to 'Deploy the init node'
4. put the localhost:3456 in the browser and the login page don't have the forms to login to alexa accunt

![Screenshot (3)](https://github.com/Apollon77/alexa-remote/assets/66877818/c93cc213-3f3f-42ab-9509-73c057f9e55c)

i type localhost:3456 and  there are no longer fields to enter username and password.

![Screenshot (2)](https://github.com/Apollon77/alexa-remote/assets/66877818/e337035b-c316-4a6c-b26c-b74d5e25f3ef)

**Comment by Mirco980** [comment]
Solved, i used 127.0.0.1:3456 and not localhost in the settings!

**Comment by Apollon77** [comment]
I have no idea what happens there, nbut the normal usecase should not be this. this is something how the node-red projectuses the alexa-remote.
