### ISSUE TITLE
no csrf found

### ISSUE THREAD

**Issue by Sk33t3rson** [Apollon77/alexa-remote#225]
**Describe the bug**  
Welp for some reason none on my alexa account is working properly. I recreated my account and the whole goto ip user name password, im using 2FA is this the culprit? I check the file path to the .txt file and nothing is being stored within the file.

Im using node red on HASSIO installed on a RPI4

and now amaozn wont grant me anymore OTP for 24 hours.. Please help

**Comment by Apollon77** [comment]
Sorry but with these information I can not help at all? This is a library and not to be used directly ... SO what exeactl did you execute? and such ... more infos please

**Comment by Sk33t3rson** [comment]
oooo close this apologies, it chased down the wrong repository
