### ISSUE TITLE
notification (timer)

### ISSUE THREAD

**Issue by jeremyarnoux** [Apollon77/alexa-remote#232]
Hi,
I'm trying to create a timer type notification. but I can not. Can you help me please
For 'value', i tested with: null, '60','60.000' and '60000'
without success

`notification = alexa.createNotificationObject('XXXXXXXXXXXXXXXXXXX', 'Timer', 'nom timer', null,'ON');
alexa.createNotification(notification, function(err,rep) { // Fix Aidom 01/03/2020
     console.log(rep);
});`

for recurrence, can you give me an example for example every tuesday and every day?

**Comment by jeremyarnoux** [comment]
the recurrence 
![image](https://github.com/Apollon77/alexa-remote/assets/16902399/8590786a-5913-49d8-945c-6193a5e69f2f)

**Comment by Apollon77** [comment]
From my knowledge timers can onlybe added using voice. only Alarm and "Reminders" can be added via the Alexa-App, and so the API.
