### ISSUE TITLE
simulate whispering textcommand to alexa

### ISSUE THREAD

**Issue by skillix** [Apollon77/alexa-remote#234]
I haven't found the possibility of whispering to Alexa, not of making her speak in a whisper, but of speaking to her in a whisper with a textcommand?

the goal being that she responds to us in a whisper, for example:

textcommand Whisper: Alexa launches Netflix
Alexa responds by whispering: ok I'm launching Netflix

**Comment by Apollon77** [comment]
Can you do that via the Alexa App? I would not know thatthis is possinle usign a routine or such ... then (sorry) no option.
