### ISSUE TITLE
failed to load notifications: "no body

### ISSUE THREAD

**Issue by brunialti** [Apollon77/alexa-remote#239]
**Describe the bug**  
Using an activity node after a nodered restart I get the "failed to load notifications: "no body"
msg. It never occourred before  (I'm using the contribute since a couple of years)

**Expected behavior**  

**Screenshots & Logfiles**  
![immagine](https://github.com/Apollon77/alexa-remote/assets/1572972/c0099463-cb13-4f12-9873-a053f68e1bae)

![immagine](https://github.com/Apollon77/alexa-remote/assets/1572972/d9f772bc-666d-4f63-91cf-753f5564896f)

**Versions:**  
adapter, js-controlle are the latest versions 
All is running on a raspberrypi 5

**Additional context**

**Comment by Apollon77** [comment]
Retry ... Amazon had issues at that time and the whole "Night". please reopen when still a topic
