### ISSUE TITLE
Sorry...we couldn't find that page

### ISSUE THREAD

**Issue by Userfrettchen** [Apollon77/alexa-remote#242]
after login in the IP:3456 i get every time the failure from Amazon
the password is correct.
![2024-05-05 16_52_37-Amazon com Page Not Found](https://github.com/Apollon77/alexa-remote/assets/76246204/f5a95fe8-12c2-4f3e-8d82-24b0287d083c)

**Comment by Apollon77** [comment]
The readme has not been consulted ;-)
https://github.com/Apollon77/alexa-remote?tab=readme-ov-file#issues-when-getting-the-cookie-and-tokens-initially

**Comment by Apollon77** [comment]
Hm ... then i would need a full debug level log - or activate 2FA and see if it works then

**Comment by Userfrettchen** [comment]
ok...i have activated 2FA and now it works

short other question...where i can found for what this refresh days are?
Because it was 3, i removed it now, because after few days alexa doesnt work. Means that, that i have to login every 3 days?

**Comment by Apollon77** [comment]
No, refresh is refreshing the cookies and tokens automatically .. the default is 4 days and normally works fine. SO if you removed that settings these 4 days should be used automatically

**Comment by Apollon77** [comment]
Without logs I can only guess ... so maybe turn on debug logging and compare logs when it works and when not? and if you like post stuff here. I use it all the time and nortmally cookies refresh ever 4 days and fr me all works

**Comment by Userfrettchen** [comment]
Where i can activate the logs?

 

Von: Ingo Fischer ***@***.***> 
Gesendet: Montag, 6. Mai 2024 08:25
An: Apollon77/alexa-remote ***@***.***>
Cc: Userfrettchen ***@***.***>; Author ***@***.***>
Betreff: Re: [Apollon77/alexa-remote] Sorry...we couldn't find that page (Issue #242)

 

Without logs I can only guess ... so maybe turn on debug logging and compare logs when it works and when not? and if you like post stuff here. I use it all the time and nortmally cookies refresh ever 4 days and fr me all works

**Comment by Apollon77** [comment]
See exmaple ... set a logger and a proper loglevel in the parameters
