### ISSUE TITLE
What is the real URL that the proxy server uses to generates this page?

### ISSUE THREAD

**Issue by danielbrunt57** [Apollon77/alexa-remote#255]
I have searched high and low through this library as well as applestrudel but I have been unable to ascertain what the real Amazon/Alexa login page URL is that the proxy server redirects to via "open http://192.168.1.104:3456 in your browser" and which looks like this:

![image](https://github.com/user-attachments/assets/4a3ef606-bb66-4061-92fc-58eae07ac85e)

Thanks!

**Comment by Apollon77** [comment]
This is a dynamically build URL ... but basically https://github.com/Apollon77/alexa-cookie/blob/master/lib/proxy.js#L192

**Comment by danielbrunt57** [comment]
That helps immensely! Thank you very much !🙏

FYI , I'm trying to fix alexa_media / alexapy / authcaptureproxy which was originally developed based on your code from years ago.  Alan developed an automated initial sign in sequence to get the initial cookie but that has recently created issues for users due to the changes Amazon made in the Alexa login windows (email & password are now two windows). That plus users getting captcha windows and/or getting prompted to provided additional one time code via SMS during first time login has everyone very frustrated.  I want to try and tear it apart and get back to basics, like how alexa-remote2 does it... User manually opens the proxy url and when it's successfully authenticated after however many windows Amazon puts you through,  return to ap/maplanding.  Right now, his sequence only allows one (email + password) or two (if OTP required) windows before returning you to the beginning to start over. His original URL used to work but now that page's selected option is to create a new account with an option to sign in existing account which, if selected, uses two separate windows for email then password.

**Comment by Apollon77** [comment]
this solution also do not work with the "old" 2FA variants using SMS or such ... but it work with the current variants, so users need to just update their OTP/2FA settings in amazon to current mechanisms and it works

**Comment by danielbrunt57** [comment]
Some users seem to get prompted upon their first log in to verify they really are in control and provide an OTP that Amazon sends to their phone (not sure about email like other manufacturers might use). I've seen that myself when I use a new browser or clear cookies but only the first time. The other users seem to always see it and I don't know if that's an issue in their browser or  account. 
Does remote2 see back and forth communication between browser and Amazon on every page change? Ie  email, then password, then OTP, then succes or only after success? Can it handle an initial captcha or, I'll call it a double-check?

**Comment by Apollon77** [comment]
As said: In this case usually users have an old OTP/2FA setting in Amazon and just need to update this to the current system. Done. I never had that old method enabled,so I never could test this and because the change is trivial I never did tries to change that in the library. The solution was always "change the etting and retry" and this works for all users so far
