### ISSUE TITLE
[Feature Request] Add endpoints for settings APIs

### ISSUE THREAD

**Issue by vijaynandwani** [Apollon77/alexa-remote#29]
Thank you for this helpful repository. I was wondering if you have any plans to add the endpoints for various settings. 

For example couple of them which might be useful are:
1) History API: Using this we can fetch the past statements which are said to alexa
2) Language: This can be used to change the language

**Comment by Apollon77** [comment]
Hi,

getHistory is already included ...

Language changing? What exactly you mean? Which implications a language change will have? maybe better to only do that via the App? :-) But in fact sure, could be added.

PRs are welcome too :-)

**Comment by Apollon77** [comment]
device settings are in ... but not language ... is that really a usecase for the lib? Then open new issue with infos
