### ISSUE TITLE
Audio tag is not working in ssml

### ISSUE THREAD

**Issue by mduzgun** [Apollon77/alexa-remote#41]
I send to ssml my Alexa device. Text can be converted speech, whispered effect is working but audio url does not work. 

        let serialOrName="G2A0WK048432057N";
        let command="ssml";
        let value='<speak><audio src="https://s3-us-west-1.amazonaws.com/sayspring-prod/media/celtic-open-chime.mp3"/> Welcome to Car-Fu.<amazon:effect name="whispered">I am not a real human.</amazon:effect>.</speak>';
        alexa.sendSequenceCommand(serialOrName, command, value, function(err, res) {
            console.log ("error: "+err)
            console.log ("result: "+res)
            if (!err && res) {
                console.log ("alexa.sendSequenceCommand is successfull");
            }

        });

logs:

deviceSerial :87c51d3bcffe48019bf9c55fb4928df6
deviceSerial :G2A0WK048432057N
deviceSerial :DB35389691CA4C4AA1037BAFEBFE9E1A
Alexa-Remote: No authentication check needed (time elapsed 6706)
Alexa-Remote: Sending Request with {"host":"pitangui.amazon.com","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}}and data={"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"operationPayload\":{\"customerId\":\"A2Q8GQKLT884AQ\",\"expireAfter\":\"PT5S\",\"content\":[{\"locale\":\"en-US\",\"display\":{\"title\":\"ioBroker\",\"body\":\"<speak><audio src=\\\"s3-us-west-1.amazonaws.com/sayspring-prod/media/celtic-open-chime.mp3\\\"/> Welcome to Car-Fu.<amazon:effect name=\\\"whispered\\\">I am not a real human.</amazon:effect>.</speak>\"},\"speak\":{\"type\":\"ssml\",\"value\":\"<speak><audio src=\\\"s3-us-west-1.amazonaws.com/sayspring-prod/media/celtic-open-chime.mp3\\\"/> Welcome to Car-Fu.<amazon:effect name=\\\"whispered\\\">I am not a real human.</amazon:effect>.</speak>\"}}],\"target\":{\"customerId\":\"A2Q8GQKLT884AQ\",\"devices\":[{\"deviceSerialNumber\":\"G2A0WK048432057N\",\"deviceTypeId\":\"A18O6U1UQFJ0XK\"}]}},\"type\":\"AlexaAnnouncement\"}}","status":"ENABLED"}

**Comment by Apollon77** [comment]
yes, this is known. Amazon seems to limit here :-( Noone found a way to play audio using SSML so far

**Comment by mduzgun** [comment]
Is there another way for play audio on Alexa pyhsical device?

**Comment by Apollon77** [comment]
nothing known
