### ISSUE TITLE
how to send custom sound to device using notification

### ISSUE THREAD

**Issue by mduzgun** [Apollon77/alexa-remote#42]
Hi, on createNotificationObject, I want to use my custom sound file (sampleUrl). So, alarm is ringing, device will play my custom audio file. I set sampleUrl =https://s3-us-west-1.amazonaws.com/sayspring-prod/media/celtic-open-chime.mp3 but it doesn't work. How to do it?

**Comment by Apollon77** [comment]
Custom SOund Files are not possible at all. Sorry
