### ISSUE TITLE
no csrf found

### ISSUE THREAD

**Issue by NebzHB** [Apollon77/alexa-remote#44]
Dear,

alot of my users receive this message the last 24h hours, are you aware Amazon changed something ?

I see you display that if this.csrf is not found in headers on getCookie ... any clue where it could come from ?

BR's

Nebz

**Comment by Apollon77** [comment]
It seems that amazon changed something. I‘m back from vacation in two days and already got some ideas from exchanges with other projects. I hope to have an update soon.

**Comment by NebzHB** [comment]
Thank your for your feedback

**Comment by mduzgun** [comment]
you can use "_cookie.localCookie" in setCookie function. It works. 

"
        else if (_cookie && _cookie.localCookie && typeof _cookie.localCookie === 'string') {
            this.cookie = _cookie.localCookie;
            this._options.formerRegistrationData = this.cookieData = _cookie;
        }
"

**Comment by Apollon77** [comment]
New version with proper solution will come tonight

**Comment by Apollon77** [comment]
fixed by 2.3.0
