### ISSUE TITLE
Hardcoded requests to amazon.de instead of using config

### ISSUE THREAD

**Issue by zyrorl** [Apollon77/alexa-remote#49]
Appears there's a tonne of requests not using this.baseUrl or the page url, instead using alexa.amazon.de which causes issues with non german alexa users.

**Comment by Apollon77** [comment]
maybe not "tonnes" but you are right ... some :-)

A PR would have also been a good idea ... Fixed by 2.5.4

**Comment by zyrorl** [comment]
@Apollon77 thanks for the effort, i was going to prepare a PR if it didnt get fixed so speedily!
