### ISSUE TITLE
WS-MQTT fail to initialize

### ISSUE THREAD

**Issue by SAABoholic** [Apollon77/alexa-remote#50]
Alexa-Remote WS-MQTT: Open: htt ps://dp-gw-na-js.amazon.com/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=**undefined**-timeserial

Alexa-Remote WS-MQTT: Initialization Msg 1 sent
Alexa-Remote WS-MQTT: Initialization Msg 2+3 sent
Initialization not done within 30s
Alexa-Remote WS-MQTT: Close: 1005
Alexa-Remote WS-MQTT: Retry Connection in **NaN**s

Any chance it might have to do with the cookie handling in alexa-wsmqtt.js since it seems to be looking for a cookie from Amazon.de ? if (cookie) serialArr = cookie.match(/ubid-**acbde**=([^;]+);/);
where's mine is from the .com, i.e. ubid-**main**=....

**Comment by Apollon77** [comment]
Try to change the code please and tell me if this works, Then I can implement both. but "acbde" is not meaning "de" btw ;-)) But es it could be that com and europe work differently sometimes

**Comment by SAABoholic** [comment]
Sorry for the delay, was traveling this weekend so I didn't have a chance to test it until now.
I did swap abcde for main and it works great with that little modification.

Thanks !

**Comment by Apollon77** [comment]
Thank you 2.5.5 should have fixed that already
