### ISSUE TITLE
Player info returns "null" for all features for one device ?

### ISSUE THREAD

**Issue by SAABoholic** [Apollon77/alexa-remote#52]
Bit weird issue, but making a Player info request works just fine for all other devices but for some reason my only Echo Dot Gen3 is returning all "null"
It's online, and I can do anything I want with it, except the get player info part....
Set volume, speak, play music etc... all works - any ideas ?

```
Alexa-Remote: Sending Request with {"host":"pitangui.amazon.com","path":"/api/np/player?deviceSerialNumber=G090...&deviceType=A32DOYMUN6DTXA&screenWidth=1392&_=","method":"GET","timeout":10000,"headers":{}}
Alexa-Remote: Response: {"playerInfo":{"hint":null,"infoText":null,"isPlayingInLemur":false,"lemurVolume":null,"lyrics":null,"mainArt":null,"mediaId":null,"miniArt":null,"miniInfoText":null,"playbackSource":null,"playingInLemurId":null,"progress":null,"provider":null,"quality":null,"queueId":null,"state":null,"template":null,"transport":null,"upNextItems":null,"volume":null}}
```

**Comment by SAABoholic** [comment]
Get Media/State says it isn't connected, but it is and as mentioned earlier, everything else works just fine....

Alexa-Remote: Sending Request with {"host":"pitangui.amazon.com","path":"/api/media/state?deviceSerialNumber=G090...&deviceType=A32DOYMUN6DTXA&screenWidth=1392&_=","method":"GET","timeout":10000,"headers":{}}
Alexa-Remote: Response: {"message":"Device is not connected/initialized: deviceSerialNumber=G090..., deviceType=A32DOYMUN6DTXA"}

**Comment by Apollon77** [comment]
The player details are cleaned out by amazon after some time after last use of player. The nulls are exactly mean that. 

So in fact the devices/amazon reset the player stuff after 1-2h. Then also a „continue playing“ is no longer possible.

**Comment by SAABoholic** [comment]
Well that's embarrassing ! :)
I've done pretty much everything except playing a song trying to figure out what the heck was going on and I do that and it's all back to normal.... LOL

Thanks for your patience !

**Comment by Apollon77** [comment]
Np, also took me some time to figure that out :-)
