### ISSUE TITLE
play TuneIn Radio

### ISSUE THREAD

**Issue by marcotchella** [Apollon77/alexa-remote#78]
Hi
i´m trying play a Tunein radio. Could you provide a example on how to do this.
Thanks

**Comment by Apollon77** [comment]
Did you checked the documentation in the Readme?

**Comment by marcotchella** [comment]
yes, but i could not find anything about Tunein

**Comment by Apollon77** [comment]
With getMusicProviders() you can get the available music providers. To Play music use     playMusicProvider(serialOrName, providerId, searchPhrase, callback) {
