### ISSUE TITLE
Enable Alexa Guard away mode

### ISSUE THREAD

**Issue by BassTeQ** [Apollon77/alexa-remote#91]
Hello, is there way to set alexa guard to away or home mode?
I don't want to have to say "Alexa I'm leaving" each time someone leaves the house, I'd like to use this module to manage it.

Thanks

**Comment by Apollon77** [comment]
Can you enable it using the Alexa App? I never saw that.

**Comment by BassTeQ** [comment]
> Can you enable it using the Alexa App? I never saw that.

Yes you just click the icon to toggle the status, but you have to first enable it in the settings.

![image](https://user-images.githubusercontent.com/32693997/94871345-1d18da80-048d-11eb-9657-1e6ea37b1a3a.png)

**Comment by Apollon77** [comment]
Is this feature already available in Germany?

**Comment by BassTeQ** [comment]
> Is this feature already available in Germany?

Check in your alexa app "settings" first as you have to choose to enable it.

![image](https://user-images.githubusercontent.com/32693997/94892371-c977b280-04c7-11eb-96f1-43c3ffaf5bdf.png)

**Comment by Apollon77** [comment]
seems then missing in germany :-(

**Comment by Apollon77** [comment]
I need a full debug log please, especially from all the "init" calls and responses- if yiu do not want to post here send via email to iobroker@fischer-ka.de with reference to this issue please

**Comment by BassTeQ** [comment]
Hi how do I get these debug logs?

**Comment by Apollon77** [comment]
ioBroker Admin: Instances - Export Mode -  Column Loglevel. Set to Debug and adapter will restart automatically.
Logfile on disk normally in /opt/iobroker/log/...

**Comment by bitmerchandise** [comment]
@BassTeQ If you install the alexa media integration in HA you will be able to do the following
![guard_node](https://user-images.githubusercontent.com/18449784/119214984-b5091a00-ba98-11eb-9898-6af7e50d7e26.jpg)

Guard should show up as an entity. This is how I enable disable guard based on whether my alarm has been armed or disarmed. You could use some sort of presence detector also to trigger the node

**Comment by Apollon77** [comment]
ure, problem is that I only have an EU account and from my  knowledge the guard is still not available there ... SO if you can somehow find out ewhat "Home asssistant" is sending out in such cases to Amazon I could rebukld it. Else I still miss the details

**Comment by Apollon77** [comment]
Ok, I did some research: It seems to be that the initial "activation" needs to be done in the Alexa App manually. Fter that the "guard mode" should be existing as a normal smart device. Can you please check and validate that?

**Comment by danielbrunt57** [comment]
@Apollon77 - This issue can be closed now since Alexa Guard is officially dead/defunct/discontinued.
See: https://reolink.com/blog/alexa-guard/
Also: https://www.pcmag.com/news/amazon-discontinues-alexa-guard-will-require-subscription-for-its-best
