### ISSUE TITLE
Voice recognition

### ISSUE THREAD

**Issue by dpayet** [Apollon77/alexa-remote#98]
Hello,

is it possible to get the detected voice with the Alexa return ? (if available).

I've created two voice profiles and I didn't find any clue about a detected voice in the returned JSON. Perhaps you have an idea ?

Thanks :)

**Comment by Apollon77** [comment]
Currently not ... The data available in the "history" (so summay and the json) is the onls stuff that is returned. I was not able to identify a user with it till now ... once the Alexa App can show you "who" said something in the history we might have a chance
